name: reputation_sensei
description: "Reputation Sensei - Staff Mobile Application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_styled_toast: ^2.2.1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  google_fonts: ^6.1.0
  photo_view: ^0.14.0
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.2
  syncfusion_flutter_signaturepad: ^24.2.3
  image_picker: ^1.0.7
  camerawesome: ^2.0.0+1
  video_player: ^2.8.2
  internet_connection_checker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
